// French version of every text marked data-i18n / data-i18n-attr in public/*.html.
// The English text lives in the HTML itself. Values may contain HTML
// (except the ones used in attributes: titles, descriptions, aria-labels).
// `npm run check:i18n` lists missing or unused keys.
export const FR = {
  // ---------- Head / accessibility ----------
  'home.title': `Stanza — Conformité, délivrabilité et suivi, réglés pour vous`,
  'home.desc': `Services techniques premium pour votre site et vos e-mails : consentement cookies, accessibilité, SPF/DKIM/DMARC, suivi côté serveur et alerte prospects. Experts vérifiés, prix fixes, suivi de 0 à 100 % et débit seulement après vérification.`,
  'home.ogtitle': `Stanza — Restez conforme. Vendez en confiance.`,
  'home.ogdesc': `Un travail premium réalisé par des experts vérifiés, à prix fixe, suivi de 0 à 100 % dans votre espace client et débité seulement une fois vérifié.`,
  'a11y.skip': `Aller au contenu principal`,
  'a11y.home': `Accueil Stanza`,
  'a11y.nav': `Navigation principale`,
  'a11y.lang': `Langue`,

  // ---------- Header ----------
  'nav.solutions': `Solutions`,
  'nav.compliance': `Conformité`,
  'nav.consent': `Consentement cookies`,
  'nav.consent.s': `Une bannière qui bloque vraiment les traceurs`,
  'nav.a11y': `Diagnostic d'accessibilité <i class="tag">Nouveau</i>`,
  'nav.a11y.s': `Repérez ce qui bloque vos clients`,
  'nav.verified': `Livraison vérifiée`,
  'nav.verified.s': `Contrôlée avant paiement`,
  'nav.inbox': `Délivrabilité e-mail`,
  'nav.tracking': `Suivi côté serveur <i class="tag">Nouveau</i>`,
  'nav.leads': `Alerte prospects <i class="tag">Nouveau</i>`,
  'nav.leads.s': `CRM + WhatsApp, e-mail ou Slack`,
  'nav.pack1.s': `Cookies + accessibilité`,
  'nav.pack2.s': `E-mails, conversions, prospects`,
  'nav.pack3': `Pack Complet <i class="tag">Les 5</i>`,
  'nav.pack3.s': `Tout en un seul passage`,
  'nav.pack4.s': `Sur devis, pour agences et groupes`,
  'nav.resources': `Ressources`,
  'nav.support': `Assistance`,
  'nav.help': `Centre d'aide`,
  'nav.help.s': `Des réponses rapides`,
  'nav.check': `Diagnostic gratuit`,
  'nav.check.s': `Nous regardons votre domaine et votre site`,
  'nav.contactus': `Nous contacter`,
  'nav.contactus.s': `Parlez à notre équipe`,
  'nav.company': `Entreprise`,
  'nav.become': `Devenir spécialiste`,
  'nav.become.s': `Rejoindre le réseau`,
  'nav.who': `Pour qui ?`,
  'nav.who.s': `Entreprises, indépendants, agences…`,
  'nav.news': `Newsletter`,
  'nav.news.s': `Actualité conformité et délivrabilité`,
  'nav.blog': `Blog`,
  'nav.blog.text': `Nos guides sur SPF, DKIM, DMARC, le consentement et l'accessibilité.`,
  'nav.blog.cta': `Lire le blog`,
  'nav.pricing': `Tarifs`,
  'nav.start': `Commencer`,
  'nav.contact': `Contacter l'équipe`,
  'nav.login': `Connexion`,

  // ---------- Hero ----------
  'hero.eyebrow': `Services premium · Conformité &amp; Revenue`,
  'hero.title': `Restez conforme.<br>Vendez en confiance.`,
  'hero.lead': `Un travail technique premium sur votre site et vos e-mails : consentement, accessibilité, délivrabilité, suivi des conversions et alerte prospects. Réalisé par des experts vérifiés, à prix fixe, suivi de 0 à 100 % dans votre espace client, et débité seulement une fois vérifié.`,
  'hero.cta': `Découvrir nos services`,
  'hero.cta2': `Pourquoi c'est important`,
  'pm.1': `Qualité premium`,
  'pm.2': `Sécurisé de bout en bout`,
  'pm.3': `Prix fixe, juste valeur`,
  'pm.4': `Suivi de 0 à 100 %`,
  'hero.tablist': `Services Stanza`,
  'tab1.label': `Délivrer`,
  'tab1.text': `SPF, DKIM et DMARC sur chaque service qui envoie en votre nom, pour que vos e-mails arrivent en boîte de réception et pas en spam.`,
  'tab2.label': `Se conformer`,
  'tab2.text': `Votre plateforme de consentement installée, et chaque script non essentiel bloqué tant que le visiteur n'a pas dit&nbsp;oui.`,
  'tab3.label': `Suivre`,
  'tab3.title': `Suivi de 0 à 100 %`,
  'tab3.text': `Suivez chaque étape depuis votre espace client. Votre carte n'est débitée qu'à 100 %, une fois le travail&nbsp;vérifié.`,
  'stage.pill': `<i>En attente</i><i>Valide</i>`,
  'stage.state': `<i>Bloqué</i><i>Chargé</i>`,
  'stage.stay': `<i>Bloqué</i><i>Bloqué</i>`,
  'stage1.steps': `<li>Audit de la zone DNS…</li><li>Publication du SPF…</li><li>Signature DKIM…</li><li>Application de DMARC…</li><li>Vérification du logo BIMI…</li>`,
  'stage1.kicker': `Authentification DNS`,
  'stage1.right': `Authentification`,
  'stage2.steps': `<li>Analyse de 42 balises…</li><li>Installation de la CMP…</li><li>Catégories de consentement…</li><li>Blocage des scripts…</li><li>Test du Consent Mode v2…</li>`,
  'stage2.banner': `<p class="consent__title">Votre vie privée compte</p><p class="consent__text">Nous utilisons des cookies de mesure et de publicité uniquement avec votre accord.</p><div class="consent__btns"><span>Tout refuser</span><span class="consent__accept">Accepter</span></div><span class="cursor" aria-hidden="true"></span>`,
  'stage2.right': `Scripts tiers`,
  'stage2.mode': `Consent Mode v2 · <b>accordé</b>`,
  'stage3.steps': `<li>Commande confirmée…</li><li>Accès reçus…</li><li>Configuration…</li><li>Tests en cours…</li><li>En attente de votre accord…</li>`,
  'stage3.brand': `Commande ST-2048`,
  'stage3.kicker': `acme.co · Pack Complet`,
  'stage3.checks': `<li>Commande confirmée</li><li>Accès reçus</li><li>Configuration terminée</li><li>Tests automatisés réussis</li><li>Rapport livré</li><li>Validé par vous</li>`,
  'stage3.right': `Avancement`,
  'stage3.escrow': `<i>Autorisé</i><i>Débité</i>`,
  'stage3.small': `Débité seulement à 100 %, après votre accord.`,

  // ---------- Services overview ----------
  'svc.eyebrow': `Ce que nous réglons`,
  'svc.title': `Deux piliers, cinq services`,
  'svc.lead': `Chaque service est un travail premium au périmètre fixe : fait une fois, fait bien, par un expert vérifié, avec un rapport de tests comme preuve. Prenez-les un par un, ou en pack pour payer moins.`,
  'svc.p1': `Conformité`,
  'svc.p1.text': `Ce que la loi attend de votre site, et qui fonctionne vraiment.`,
  'svc.p2.text': `Ce qui transforme vos e-mails, vos publicités et vos formulaires en ventes.`,
  'svc.packs': `Besoin de plusieurs services ? Les packs <a href="/pricing#pack-compliance">Conformité</a>, <a href="/pricing#pack-revenue">Revenue</a> et <a href="/pricing#pack-complete">Complet</a> les regroupent en un seul passage, avec un seul spécialiste.`,
  'pro.eyebrow': `Nos engagements`,
  'pro.title': `Qualité premium, esprit tranquille`,
  'pro.lead': `Quatre engagements derrière chaque commande, quelle que soit sa taille.`,
  'pro.1.t': `Premium, par défaut`,
  'pro.1': `Des experts vérifiés, un travail soigné sur votre configuration réelle, un seul interlocuteur et un rapport détaillé à partager avec votre équipe, votre DPO ou vos clients.`,
  'pro.2.t': `Sécurisé à chaque étape`,
  'pro.2': `Paiement par Stripe, accès temporaires uniquement, contrôles automatisés avant livraison, et votre carte n'est débitée qu'après votre accord.`,
  'pro.3.t': `Le juste prix`,
  'pro.3': `Un travail d'expert à prix fixe : pas de devis à relancer, pas d'abonnement, pas de surprise. Les packs coûtent moins cher que les mêmes services pris séparément.`,
  'pro.4.t': `Suivi de 0 à 100 %`,
  'pro.4': `Dans votre espace client, suivez chaque étape de votre commande : accès reçus, configuration, tests, rapport final. Vous savez toujours où en est le travail.`,

  // ---------- Deliverability ----------
  'deliv.eyebrow': `Délivrabilité e-mail`,
  'deliv.title': `En boîte de réception, pas dans les spams`,
  'deliv.body': `Google, Yahoo et Microsoft rejettent désormais les e-mails non authentifiés. Un devis qui part en spam est un devis que personne ne lit. Stanza configure SPF, DKIM, DMARC, BIMI et MX sur votre domaine, pour que chaque facture, relance et newsletter arrive chez la bonne personne.`,
  'deliv.cta': `Sécuriser mes e-mails`,
  'deliv.typing': `Régler la délivrabilité de acme.co`,
  'deliv.to': `à moi · Principale`,
  'deliv.inbox': `Réception`,
  'deliv.subject': `Votre facture de mars est disponible`,
  'deliv.report': `Rapport DMARC`,
  'deliv.aligned': `alignés`,
  'deliv.f1': `Authentification DNS complète pour chaque service qui envoie en votre nom : Google Workspace, Microsoft 365, votre CRM et votre outil de newsletter.`,
  'deliv.f2.t': `BIMI et enregistrements MX`,
  'deliv.f2': `Votre logo à côté de vos e-mails dans les messageries compatibles, un routage MX propre et aucun enregistrement contradictoire.`,
  'deliv.f3.t': `Vérification Postmaster`,
  'deliv.f3': `Google Postmaster Tools et rapports DMARC en place : vous voyez la réputation de votre domaine au lieu de la deviner.`,

  // ---------- Compliance ----------
  'head.title': `Là où l'audit s'arrête,<br>le correctif commence...`,
  'comp.banner': `<b>Cookies ?</b><small>Mesure et publicité uniquement avec votre accord.</small><span class="browser__btns"><i>Refuser</i><i>Accepter</i></span>`,
  'comp.cats': `Catégories de consentement`,
  'comp.toggles': `<li>Nécessaires<span class="toggle is-on is-locked"></span></li><li>Mesure d'audience<span class="toggle" data-toggle></span></li><li>Marketing<span class="toggle"></span></li>`,
  'comp.blocked': `<b>12</b> scripts bloqués avant consentement`,
  'comp.eyebrow': `Cookies et accessibilité`,
  'comp.title': `Le consentement d'abord, sur chaque page`,
  'comp.body': `Une bannière seule ne prouve rien si vos balises se déclenchent quand même. Nous déployons Axeptio, Cookiebot ou Didomi sur Shopify, Webflow ou WordPress et bloquons chaque script non essentiel jusqu'à l'accord du visiteur. Puis nous repérons ce qui empêche vos clients en situation de handicap d'acheter.`,
  'comp.cta': `Mettre mon site en conformité`,
  'comp.f1.t': `Un consentement qui tient`,
  'comp.f1': `Axeptio, Cookiebot ou Didomi, configurés avec vos catégories et votre charte, testés avant et après consentement, avec un rapport pour votre DPO.`,
  'comp.f2.t': `Blocage des scripts et Consent Mode v2`,
  'comp.f2': `Mesure d'audience, pixels et widgets attendent le consentement. Google Consent Mode v2 est branché pour que vos mesures restent exploitables.`,
  'comp.f3.t': `Diagnostic d'accessibilité`,
  'comp.f3': `Vos pages clés analysées, de l'accueil au paiement, et une liste de correctifs priorisée pour votre développeur. Une première étape avant un audit complet.`,

  // ---------- Revenue & Data ----------
  'tag.new': `Nouveau`,
  'rev.title': `Chaque conversion comptée, chaque prospect rappelé`,
  'rev.body': `Les bloqueurs de publicités et les restrictions des navigateurs cachent une partie de vos ventes à vos outils publicitaires, et un prospect qui attend va voir ailleurs. Nous envoyons vos conversions côté serveur, dans le respect du consentement, et alertons votre équipe dès qu'une demande arrive.`,
  'rev.cta': `Fiabiliser mon suivi`,
  'rev.events': `Événements serveur`,
  'rev.list': `<li><b>Purchase</b><span>navigateur + serveur</span><i>dédupliqué</i></li><li><b>Lead</b><span>navigateur + serveur</span><i>dédupliqué</i></li><li><b>AddToCart</b><span>serveur</span><i>reçu</i></li>`,
  'rev.lead': `Nouveau prospect · formulaire du site<b>Ajouté au CRM, équipe alertée</b>`,
  'rev.consent': `Consentement respecté<b>Seules les données autorisées partent</b>`,
  'rev.f1.t': `GTM côté serveur`,
  'rev.f1': `Vos événements envoyés depuis un sous-domaine qui vous appartient : moins de conversions perdues à cause des bloqueurs et des restrictions des navigateurs.`,
  'rev.f2.t': `API Conversions Meta`,
  'rev.f2': `Événements navigateur et serveur dédupliqués, avec un plan de tests qui montre ce qui est reçu et la qualité de la correspondance.`,
  'rev.f3.t': `Alerte prospect instantanée`,
  'rev.f3': `Un scénario Make ou Zapier ajoute chaque prospect à votre CRM et prévient votre équipe sur WhatsApp, par e-mail ou sur Slack en quelques secondes.`,

  // ---------- Verification ----------
  'ver.gate': `Validation`,
  'ver.list': `<li>Requêtes DNS</li><li>Test de réception</li><li>Consentement avant balises</li><li>Accord du client</li>`,
  'ver.escrow': `Paiement<b>Débité après votre accord</b>`,
  'ver.match': `Avancement<b>72 % · tests en cours</b>`,
  'ver.eyebrow': `Livraison suivie et vérifiée`,
  'ver.title': `Suivez chaque étape. Payez à 100 %.`,
  'ver.body': `Votre commande avance de 0 à 100 % sous vos yeux, dans votre espace client. Avant la livraison, une étape de validation lance requêtes DNS, e-mails tests et contrôle du chargement des scripts. Votre carte est autorisée à la commande et débitée seulement après votre accord.`,
  'ver.cta': `Voir comment ça marche`,
  'ver.f1.t': `Délais garantis`,
  'ver.f1': `Standard en 5 jours ouvrés, Express en 48 h, Flash en 24 h. En retard ? Vous êtes remboursé de 50 % du prix HT en Standard, de 100 % en Express ou en Flash.`,
  'ver.f2.t': `Suivi en temps réel`,
  'ver.f2': `Chaque étape de votre commande est visible dans votre espace client, des accès reçus jusqu'au rapport de tests final.`,
  'ver.f3.t': `Paiement à la livraison vérifiée`,
  'ver.f3': `Paiement sécurisé par Stripe : votre carte est autorisée à la commande et débitée seulement une fois le travail vérifié et validé par vous.`,

  // ---------- Why it matters / audiences ----------
  'aud.eyebrow': `Pourquoi c'est important`,
  'aud.title': `Grande ou petite structure, les règles et les enjeux sont les mêmes`,
  'aud.lead': `Les messageries, les régulateurs et vos clients ne font pas de différence selon votre taille. Ce qui change, c'est ce qu'une erreur vous coûte.`,
  'aud.s1.l': `Messageries`,
  'aud.s1': `Depuis février 2024, Gmail et Yahoo exigent SPF, DKIM et DMARC des expéditeurs en volume, et Outlook a suivi en 2025. Les e-mails non authentifiés sont filtrés ou rejetés.`,
  'aud.s2.l': `Accessibilité`,
  'aud.s2': `Depuis le 28 juin 2025, l'European Accessibility Act s'applique à de nombreux sites de vente en ligne de l'Union européenne, hors micro-entreprises. Chaque client bloqué est une vente perdue.`,
  'aud.s3.l': `Cookies`,
  'aud.s3': `La CNIL et ses homologues européens contrôlent les sites qui déposent des traceurs sans consentement, et sanctionnent des organisations de toutes tailles, du grand groupe à la petite entreprise.`,
  'aud.for': `Recommandé`,
  'aud.c1.t': `Grandes entreprises`,
  'aud.c1': `Des dizaines d'outils envoient des e-mails et déposent des traceurs en votre nom. Un seul service mal configuré suffit à envoyer tout un domaine en spam, ou à exposer votre marque au régulateur.`,
  'aud.c2.t': `PME et ETI`,
  'aud.c2': `Pas d'expert en interne, mais les mêmes obligations que les grands groupes. Un devis qui part en spam ou une bannière qui trace avant le consentement vous coûte des ventes et vous expose.`,
  'aud.c3.t': `E-commerçants`,
  'aud.c3': `L'accessibilité est désormais attendue jusqu'au paiement, chaque conversion manquée par vos outils affaiblit vos campagnes, et chaque demande sans réponse est un panier qui part ailleurs.`,
  'aud.c4.t': `Indépendants et particuliers`,
  'aud.c4': `Un site vitrine, un portfolio, votre propre nom de domaine pour vos e-mails : vos devis et vos réponses doivent arriver, et dès que votre site utilise de la mesure d'audience ou de la publicité, le consentement des visiteurs s'applique à vous aussi.`,
  'aud.c5.t': `Agences`,
  'aud.c5': `La conformité et la délivrabilité de vos clients rejaillissent sur vous. Confiez la partie technique à un spécialiste et livrez un rapport de tests partageable à chaque client.`,
  'aud.c6.t': `Associations et startups`,
  'aud.c6': `Appels aux dons, newsletters, formulaires d'inscription : vos messages doivent arriver, et les personnes qui vous font confiance méritent un consentement propre dès le premier jour, sans recruter une équipe pour ça.`,
  'aud.cta.text': `Vous ne savez pas par où commencer ? Parlez-nous de votre site, nous vous orientons vers le bon service.`,
  'aud.cta1': `Demander un diagnostic gratuit`,
  'aud.cta2': `Voir les offres et tarifs`,

  // ---------- Standards / why / integrations ----------
  'std.title': `Conçu selon les règles des messageries et des régulateurs`,
  'std.gdpr': `<span class="is-on">RGPD</span><span>ePrivacy</span>`,
  'why.label': `Pourquoi Stanza`,
  'why.bullets': `Choisir une diapositive`,
  'why.1.l': `Qualité premium`,
  'why.1': `Des experts vérifiés, un travail soigné, un rapport que vous serez fier de partager.`,
  'why.2.l': `Rapport qualité/prix`,
  'why.2': `Un travail d'expert à prix fixe. Pas de devis, pas d'abonnement, pas de surprise.`,
  'why.3.l': `Suivi de 0 à 100 %`,
  'why.3': `Suivez votre commande étape par étape depuis votre espace client.`,
  'why.4.l': `Paiement sécurisé par Stripe`,
  'why.4': `Votre carte n'est débitée qu'à 100 %, une fois la livraison vérifiée.`,
  'why.5.l': `Réseau de spécialistes`,
  'why.5': `Des spécialistes vérifiés, choisis pour votre tâche.`,
  'why.6.l': `La vitesse quand il le faut`,
  'why.6': `Standard en 5 jours, Express en 48 h, Flash en 24 h. Garanti, ou remboursé.`,
  'why.cta': `Voir les offres et tarifs`,
  'int.title': `Compatible avec vos outils`,
  'int.cta': `Une question sur vos outils ?`,

  // ---------- FAQ (home) ----------
  'faq.title': `Vos questions, nos réponses`,
  'faq.1.q': `De quoi avez-vous besoin pour commencer ?`,
  'faq.1.a': `Après le paiement, un court formulaire vous demande votre domaine, votre messagerie, la plateforme de votre site et un moyen de nous donner un accès temporaire à votre hébergeur DNS, à votre CMS ou à vos outils. Votre spécialiste commence dès que l'accès est confirmé.`,
  'faq.2.q': `Quand ma carte est-elle débitée ?`,
  'faq.2.a': `À la commande, Stripe autorise votre carte. Le montant n'est prélevé qu'une fois la validation réussie et le rapport de livraison approuvé par vous, sous 7 jours. Si le travail ne passe pas la validation, l'autorisation est levée et vous ne payez rien.`,
  'faq.7.q': `Comment suivre ma commande ?`,
  'faq.7.a': `Depuis votre espace client, vous voyez votre commande avancer de 0 à 100 % : accès reçus, configuration, tests, rapport final. C'est aussi là que vous validez la livraison avant que votre carte soit débitée.`,
  'faq.3.q': `En combien de temps livrez-vous ?`,
  'faq.3.a': `La livraison standard prend 5 jours ouvrés. Si vous êtes pressé, choisissez Express (48 h maximum) ou Flash (24 h maximum) sur la page des tarifs. Chaque délai est garanti : en cas de retard, vous êtes remboursé de 50 % du prix HT en Standard et de 100 % du prix HT en Express ou en Flash.`,
  'faq.4.q': `Mes e-mails ne partiront-ils plus en spam ?`,
  'faq.4.a': `L'authentification est la base que Google, Yahoo et Microsoft exigent désormais pour arriver en boîte de réception. Nous la configurons et la vérifions de bout en bout. Le contenu et la réputation d'envoi comptent aussi : votre rapport contient des recommandations sur ces deux points.`,
  'faq.5.q': `Quels outils et plateformes prenez-vous en charge ?`,
  'faq.5.a': `Axeptio, Cookiebot et Didomi sur Shopify, Webflow et WordPress ; Google Workspace et Microsoft 365 pour les e-mails ; Google Tag Manager et Meta pour le suivi ; Make ou Zapier pour les automatisations. Si vos outils sont différents, contactez-nous : nous vous disons sous 24 h si cela rentre dans nos services.`,
  'faq.6.q': `Faites-vous du conseil juridique ?`,
  'faq.6.a': `Non. Stanza réalise la mise en œuvre technique. Votre politique de confidentialité et vos bases légales doivent être validées par votre DPO ou votre conseil, et le diagnostic d'accessibilité n'est ni un audit RGAA complet ni une attestation de conformité.`,
  'cta.title': `Un travail premium,<br>suivi jusqu'à 100 %.`,
  'cta.btn': `Voir les offres et tarifs`,

  // ---------- Footer ----------
  'ft.product': `Produit`,
  'ft.who': `Pour qui ?`,
  'ft.agencies': `Agences`,
  'ft.services': `Services`,
  'ft.a11y': `Diagnostic d'accessibilité`,
  'ft.tracking': `Suivi côté serveur`,
  'ft.leads': `Alerte prospects`,
  'ft.verification': `Vérification`,
  'ft.pay': `Paiement à la livraison`,
  'ft.platforms': `Plateformes`,
  'ft.websites': `Sites web`,
  'ft.email': `Messageries`,
  'ft.tracktools': `Suivi et automatisation`,
  'ft.cmp': `Plateformes de consentement`,
  'ft.faq': `FAQ tarifs`,
  'ft.about': `Qui sommes-nous`,
  'ft.aboutus': `À propos`,
  'ft.legal': `Mentions légales`,
  'ft.privacy': `Politique de confidentialité`,
  'ft.terms': `Conditions générales de vente`,
  'ft.cookies': `Gérer les cookies`,
  'ft.abuse': `Signaler un abus`,

  // ---------- Pricing page ----------
  'pr.title': `Tarifs — Stanza`,
  'pr.desc': `Services premium à prix fixes : consentement cookies, accessibilité, délivrabilité e-mail, suivi côté serveur et alerte prospects. Suivis de 0 à 100 %, débités seulement après vérification.`,
  'pr.ogtitle': `Tarifs Stanza — une tâche, un prix fixe`,
  'pr.eyebrow': `Tarifs`,
  'pr.h1': `Un travail premium. Un prix fixe.<br>Payé seulement à 100 %.`,
  'pr.lead': `Un travail d'expert au périmètre et au prix fixes, hors taxes : pas de devis, pas d'abonnement, pas de surprise. Vous suivez votre commande de 0 à 100 % dans votre espace client, et votre carte n'est débitée qu'une fois la livraison vérifiée.`,
  'pr.pt1': `Qualité premium, experts vérifiés`,
  'pr.pt2': `Paiement sécurisé, débité après validation`,
  'pr.pt3': `Prix fixe, sans abonnement`,
  'pr.pt4': `Suivi de 0 à 100 %`,
  'pr.speed': `Délai de livraison`,
  'pr.speed.std': `5 jours ouvrés`,
  'pr.speed.exp': `48 h maximum`,
  'pr.speed.fla': `24 h maximum`,
  'gt.title': `Délai garanti, ou remboursé`,
  'gt.text': `Si nous dépassons le délai choisi, vous êtes remboursé de <b>50 % du prix HT en Standard</b> et de <b>100 % du prix HT en Express ou en Flash</b>. Le délai démarre dès que nous avons tous les accès nécessaires.`,
  'pr.error': `Le paiement n'a pas pu démarrer. Réessayez ou contactez-nous.`,
  'pr.packs.t': `Plusieurs services, un seul passage, un meilleur prix`,
  'pr.packs.l': `Notre meilleur rapport qualité/prix : un seul expert s'occupe de tout dans le bon ordre, avec un rapport regroupé, pour moins cher que les mêmes services pris séparément.`,
  'pr.p1.e': `Pilier 1`,
  'pr.p1.t': `Conformité`,
  'pr.p1.l': `Ce que la loi attend de votre site : un consentement qui tient vraiment, et un premier regard sur l'accessibilité.`,
  'pr.p2.e': `Pilier 2`,
  'pr.p2.l': `Ce qui transforme vos e-mails, vos publicités et vos formulaires en ventes : des messages qui arrivent, des conversions comptées, des prospects rappelés vite.`,
  'pr.m.e': `Volume`,
  'pr.m.t': `Plusieurs domaines à authentifier ?`,
  'pr.m.l': `Pour les agences et les groupes multi-marques. Indiquez le nombre de domaines à traiter : un expert vous répond avec un devis et une estimation du temps nécessaire, dans votre espace client.`,
  'pr.how.t': `Comment se passe une commande`,
  'pr.how.1.t': `Vous choisissez et commandez`,
  'pr.how.1': `Paiement sécurisé par Stripe. Votre carte est autorisée, pas débitée.`,
  'pr.how.2.t': `Vous partagez vos accès`,
  'pr.how.2': `Un formulaire de 2 minutes : votre domaine, votre site, vos outils et comment nous donner un accès temporaire.`,
  'pr.how.3.t': `Vous suivez de 0 à 100 %`,
  'pr.how.3': `Un expert vérifié réalise le travail dans le délai choisi ; vous suivez chaque étape dans votre espace client.`,
  'pr.how.4.t': `Vous validez, puis vous payez`,
  'pr.how.4': `Contrôles automatisés et rapport de tests. Votre carte n'est débitée qu'après votre accord.`,
  'pr.faq.t': `Questions sur les tarifs`,
  'pr.faq.1.q': `Les prix sont-ils hors taxes ?`,
  'pr.faq.1.a': `Oui. Tous les prix de cette page sont affichés hors taxes (HT) et sont des paiements uniques, sans abonnement.`,
  'pr.faq.2.q': `Quelle différence entre Standard, Express et Flash ?`,
  'pr.faq.2.a': `Le travail et le rapport sont exactement les mêmes ; seul le délai change. Standard : 5 jours ouvrés. Express : 48 h maximum. Flash : 24 h maximum. Le délai démarre dès que nous avons les accès nécessaires, et il est garanti : en cas de retard, vous êtes remboursé de 50 % du prix HT en Standard, de 100 % du prix HT en Express ou en Flash.`,
  'pr.faq.8.q': `Que se passe-t-il si le délai n'est pas tenu ?`,
  'pr.faq.8.a': `Vous êtes remboursé. En Standard, nous remboursons la moitié du prix HT ; en Express ou en Flash, la totalité du prix HT. Le travail est tout de même terminé et livré. Le délai court à partir du moment où nous avons tous les accès nécessaires. Les demandes multi-domaines sur devis ne sont pas concernées : leur délai est fixé dans le devis.`,
  'pr.faq.3.q': `Quand ma carte est-elle débitée ?`,
  'pr.faq.3.a': `À la commande, Stripe autorise seulement votre carte. Le montant est prélevé une fois la validation réussie et le rapport de livraison approuvé par vous, sous 7 jours. Si le travail ne passe pas la validation, l'autorisation est levée et vous ne payez rien.`,
  'pr.faq.4.q': `Les licences des logiciels sont-elles incluses ?`,
  'pr.faq.4.a': `Non. Les abonnements aux outils tiers (plateforme de consentement, hébergement du serveur de suivi, Make, Zapier, CRM, WhatsApp) sont facturés par leurs éditeurs. Chaque fiche indique précisément ce qui est inclus et ce qui ne l'est pas.`,
  'pr.faq.5.q': `Pourquoi le suivi côté serveur demande-t-il un consentement en place ?`,
  'pr.faq.5.a': `Le suivi côté serveur ne remplace pas le consentement : il n'envoie que les données que vos visiteurs ont autorisées. Si vous n'avez pas encore de plateforme de consentement conforme, le Pack Complet l'installe d'abord, puis branche le suivi.`,
  'pr.faq.6.q': `J'ai plusieurs sites ou domaines, ou un besoin particulier.`,
  'pr.faq.6.a': `Pour plusieurs domaines e-mail, utilisez la demande de devis multi-domaines : indiquez le nombre de domaines et un expert vous envoie un devis avec une estimation du délai. Pour tout le reste, <a href="#" data-tally="contact">contactez-nous</a> : nous répondons sous 24 h.`,
  'pr.cta.t': `Premium, sécurisé, suivi à 100 %.<br>Lequel vous faut-il ?`,

  // ---------- Success page ----------
  'ok.title': `Commande confirmée — Stanza`,
  'ok.h1': `Commande confirmée.<br>Passons à la mise en route.`,
  'ok.lead': `Votre carte a été autorisée. Elle ne sera débitée qu'une fois votre livraison validée par tous les contrôles.`,
  'ok.s1': `Parlez-nous de votre domaine, de votre site et de vos outils (2 minutes).`,
  'ok.s2': `Un spécialiste vérifié est attribué et commence le travail.`,
  'ok.s3': `Suivez votre commande de 0 à 100 % dans votre espace client, puis validez le rapport de tests dans le délai choisi.`,
  'ok.cta': `Compléter la mise en route`,
  'ok.back': `Retour à Stanza`,
};
