// French version of every text marked data-i18n / data-i18n-attr in public/*.html.
// The English text lives in the HTML itself. Values may contain HTML
// (except the ones used in attributes: titles, descriptions, aria-labels).
// `npm run check:i18n` lists missing or unused keys.
export const FR = {
  // ---------- Head / accessibility ----------
  'home.title': `Stanza — Conformité, délivrabilité et suivi, réglés pour vous`,
  'home.desc': `Services techniques premium pour votre site et vos e-mails : consentement cookies, accessibilité, SPF/DKIM/DMARC, suivi côté serveur et alerte prospects. Experts vérifiés, prix fixes, suivi de 0 à 100 % et débit seulement après vérification.`,
  'home.ogtitle': `Stanza — Ne laissez plus un problème technique bloquer votre croissance.`,
  'home.ogdesc': `Un travail premium réalisé par des experts vérifiés, à prix fixe, suivi de 0 à 100 % dans votre espace client et débité seulement une fois vérifié.`,
  'a11y.skip': `Aller au contenu principal`,
  'a11y.home': `Accueil Stanza`,
  'a11y.nav': `Navigation principale`,
  'a11y.lang': `Langue`,

  // ---------- Header ----------
  'nav.solutions': `Solutions`,
  'nav.compliance': `Conformité`,
  'nav.consent': `Consentement cookies`,
  'nav.consent.s': `Une bannière qui bloque vraiment les traceurs`,
  'nav.a11y': `Diagnostic d'accessibilité <i class="tag">Nouveau</i>`,
  'nav.a11y.s': `Repérez ce qui bloque vos clients`,
  'nav.verified': `Livraison vérifiée`,
  'nav.verified.s': `Contrôlée avant paiement`,
  'nav.inbox': `Délivrabilité e-mail`,
  'nav.tracking': `Suivi côté serveur <i class="tag">Nouveau</i>`,
  'nav.leads': `Alerte prospects <i class="tag">Nouveau</i>`,
  'nav.leads.s': `CRM + WhatsApp, e-mail ou Slack`,
  'nav.pack1.s': `Cookies + accessibilité`,
  'nav.pack2.s': `E-mails, conversions, prospects`,
  'nav.pack3': `Pack Complet <i class="tag">Les 5</i>`,
  'nav.pack3.s': `Tout en un seul passage`,
  'nav.pack4.s': `Sur devis, pour agences et groupes`,
  'nav.resources': `Ressources`,
  'nav.support': `Assistance`,
  'nav.help': `Centre d'aide`,
  'nav.help.s': `Des réponses rapides`,
  'nav.check': `Diagnostic gratuit`,
  'nav.check.s': `Nous regardons votre domaine et votre site`,
  'nav.contactus': `Nous contacter`,
  'nav.contactus.s': `Parlez à notre équipe`,
  'nav.company': `Entreprise`,
  'nav.become': `Devenir spécialiste`,
  'nav.become.s': `Rejoindre le réseau`,
  'nav.who': `Pour qui ?`,
  'nav.who.s': `Entreprises, indépendants, agences…`,
  'nav.news': `Newsletter`,
  'nav.news.s': `Actualité conformité et délivrabilité`,
  'nav.blog': `Blog`,
  'nav.blog.text': `Nos guides sur SPF, DKIM, DMARC, le consentement et l'accessibilité.`,
  'nav.blog.cta': `Lire le blog`,
  'nav.pricing': `Tarifs`,
  'nav.start': `Commencer`,
  'nav.contact': `Contacter l'équipe`,
  'nav.login': `Connexion`,

  // ---------- Hero ----------
  'hero.eyebrow': `Des services de qualité et durables qui font la différence`,
  'hero.title': `Ne laissez plus un problème technique bloquer votre croissance.`,
  'hero.lead': `Un travail technique sur votre site et vos e-mails : consentement, accessibilité, délivrabilité, suivi des conversions, alerte prospects et bien d'autres prochainement. Réalisé par des experts vérifiés, à prix fixe, suivi du début à la fin dans votre espace client, et débité seulement une fois vérifié.`,
  'hero.cta': `Découvrir nos services`,
  'hero.cta2': `Pourquoi c'est important`,
  'pm.1': `Zéro temps perdu en recrutement`,
  'pm.2': `Prix fixe sans surprise`,
  'pm.3': `Résultat conforme assuré par des experts de confiance`,
  'pm.4': `Délai d'urgence garanti ou remboursé`,
  'hero.tablist': `Services Stanza`,
  'tab1.label': `Revenue &amp; Data`,
  'tab1.title': `Des ventes qui ne vous échappent plus`,
  'tab1.text': `Des e-mails perdus dans les spams, des conversions que vos outils publicitaires ne voient jamais, des prospects qui attendent une réponse : autant de ventes qui filent sans même que vous le&nbsp;sachiez.`,
  'tab2.label': `Se conformer`,
  'tab2.title': `Nouvelles obligations européennes`,
  'tab2.text': `L'accessibilité est obligatoire pour de nombreux sites marchands depuis juin 2025, et le consentement aux cookies est contrôlé de près. Se mettre en règle dès maintenant, c'est éviter les sanctions et ne refuser aucun&nbsp;client.`,
  'tab3.label': `Suivre`,
  'tab3.title': `Suivi complet`,
  'tab3.text': `Suivez chaque étape depuis votre espace client. Votre carte n'est débitée qu'à 100 %, une fois le travail&nbsp;vérifié.`,
  'stage.pill': `<i>En attente</i><i>Valide</i>`,
  'stage.state': `<i>Bloqué</i><i>Chargé</i>`,
  'stage.stay': `<i>Bloqué</i><i>Bloqué</i>`,
  'stage1.steps': `<li>Audit de la zone DNS…</li><li>Publication du SPF…</li><li>Signature DKIM…</li><li>Application de DMARC…</li><li>Vérification du logo BIMI…</li>`,
  'stage1.kicker': `Authentification DNS`,
  'stage1.right': `Authentification`,
  'stage2.steps': `<li>Analyse de 42 balises…</li><li>Installation de la CMP…</li><li>Catégories de consentement…</li><li>Blocage des scripts…</li><li>Test du Consent Mode v2…</li>`,
  'stage2.banner': `<p class="consent__title">Votre vie privée compte</p><p class="consent__text">Nous utilisons des cookies de mesure et de publicité uniquement avec votre accord.</p><div class="consent__btns"><span>Tout refuser</span><span class="consent__accept">Accepter</span></div><span class="cursor" aria-hidden="true"></span>`,
  'stage2.right': `Scripts tiers`,
  'stage2.mode': `Consent Mode v2 · <b>accordé</b>`,
  'stage3.steps': `<li>Commande confirmée…</li><li>Accès reçus…</li><li>Configuration…</li><li>Tests en cours…</li><li>En attente de votre accord…</li>`,
  'stage3.brand': `Commande ST-2048`,
  'stage3.kicker': `acme.co · Pack Complet`,
  'stage3.checks': `<li>Commande confirmée</li><li>Accès reçus</li><li>Configuration terminée</li><li>Tests automatisés réussis</li><li>Rapport livré</li><li>Validé par vous</li>`,
  'stage3.right': `Avancement`,
  'stage3.escrow': `<i>Autorisé</i><i>Débité</i>`,
  'stage3.small': `Débité seulement à 100 %, après votre accord.`,

  // ---------- Services overview ----------
  'svc.eyebrow': `Ce que nous réglons`,
  'svc.title': `Deux piliers, cinq services`,
  'svc.lead': `Chaque service est un travail premium au périmètre fixe : fait une fois, fait bien, par un expert vérifié, avec un rapport de tests comme preuve. Prenez-les un par un, ou en pack pour payer moins.`,
  'svc.p1': `Conformité`,
  'svc.p1.text': `Ce que la loi attend de votre site, et qui fonctionne vraiment.`,
  'svc.p2.text': `Ce qui transforme vos e-mails, vos publicités et vos formulaires en ventes.`,
  'svc.packs': `Besoin de plusieurs services ? Les packs <a href="/pricing#pack-compliance">Conformité</a>, <a href="/pricing#pack-revenue">Revenue</a> et <a href="/pricing#pack-complete">Complet</a> les regroupent en un seul passage, avec un seul spécialiste.`,
  'pro.eyebrow': `Nos engagements`,
  'pro.title': `Qualité premium, esprit tranquille`,
  'pro.lead': `Quatre engagements derrière chaque commande, quelle que soit sa taille.`,
  'pro.1.t': `Premium, par défaut`,
  'pro.1': `Des experts vérifiés, un travail soigné sur votre configuration réelle, un seul interlocuteur et un rapport détaillé à partager avec votre équipe, votre DPO ou vos clients.`,
  'pro.2.t': `Sécurisé à chaque étape`,
  'pro.2': `Paiement par Stripe, accès temporaires uniquement, contrôles automatisés avant livraison, et votre carte n'est débitée qu'après votre accord.`,
  'pro.3.t': `Le juste prix`,
  'pro.3': `Un travail d'expert à prix fixe : pas de devis à relancer, pas d'abonnement, pas de surprise. Les packs coûtent moins cher que les mêmes services pris séparément.`,
  'pro.4.t': `Suivi de 0 à 100 %`,
  'pro.4': `Dans votre espace client, suivez chaque étape de votre commande : accès reçus, configuration, tests, rapport final. Vous savez toujours où en est le travail.`,

  // ---------- Deliverability ----------
  'deliv.eyebrow': `Délivrabilité e-mail`,
  'deliv.title': `En boîte de réception, pas dans les spams`,
  'deliv.body': `Google, Yahoo et Microsoft rejettent désormais les e-mails non authentifiés. Un devis qui part en spam est un devis que personne ne lit. Stanza configure SPF, DKIM, DMARC, BIMI et MX sur votre domaine, pour que chaque facture, relance et newsletter arrive chez la bonne personne.`,
  'deliv.cta': `Sécuriser mes e-mails`,
  'deliv.typing': `Régler la délivrabilité de acme.co`,
  'deliv.to': `à moi · Principale`,
  'deliv.inbox': `Réception`,
  'deliv.subject': `Votre facture de mars est disponible`,
  'deliv.report': `Rapport DMARC`,
  'deliv.aligned': `alignés`,
  'deliv.f1': `Authentification DNS complète pour chaque service qui envoie en votre nom : Google Workspace, Microsoft 365, votre CRM et votre outil de newsletter.`,
  'deliv.f2.t': `BIMI et enregistrements MX`,
  'deliv.f2': `Votre logo à côté de vos e-mails dans les messageries compatibles, un routage MX propre et aucun enregistrement contradictoire.`,
  'deliv.f3.t': `Vérification Postmaster`,
  'deliv.f3': `Google Postmaster Tools et rapports DMARC en place : vous voyez la réputation de votre domaine au lieu de la deviner.`,

  // ---------- Compliance ----------
  'head.title': `Là où l'audit s'arrête,<br>le correctif commence...`,
  'comp.banner': `<b>Cookies ?</b><small>Mesure et publicité uniquement avec votre accord.</small><span class="browser__btns"><i>Refuser</i><i>Accepter</i></span>`,
  'comp.cats': `Catégories de consentement`,
  'comp.toggles': `<li>Nécessaires<span class="toggle is-on is-locked"></span></li><li>Mesure d'audience<span class="toggle" data-toggle></span></li><li>Marketing<span class="toggle"></span></li>`,
  'comp.blocked': `<b>12</b> scripts bloqués avant consentement`,
  'comp.eyebrow': `Cookies et consentement`,
  'comp.title': `Le consentement d'abord, sur chaque page`,
  'comp.body': `Une bannière seule ne prouve rien si vos balises se déclenchent quand même. Nous déployons Axeptio, Cookiebot ou Didomi sur Shopify, Webflow ou WordPress et bloquons chaque script non essentiel jusqu'à l'accord du visiteur.`,
  'comp.cta': `Mettre mon site en conformité`,
  'comp.f1.t': `Un consentement qui tient`,
  'comp.f1': `Axeptio, Cookiebot ou Didomi, configurés avec vos catégories et votre charte, testés avant et après consentement, avec un rapport pour votre DPO.`,
  'comp.f2.t': `Blocage des scripts et Consent Mode v2`,
  'comp.f2': `Mesure d'audience, pixels et widgets attendent le consentement. Google Consent Mode v2 est branché pour que vos mesures restent exploitables.`,
  'comp.f3.t': `Tous les sites`,
  'comp.f3': `Thèmes Shopify, projets Webflow et sites WordPress, y compris les balises injectées par les applications, les extensions et Google Tag Manager.`,
  'trk.direct': `Bloqué par le navigateur`,
  'trk.n1': `Navigateur`,
  'trk.n1s': `Visiteur`,
  'trk.n2': `Votre serveur`,
  'trk.n3': `Outils publicitaires`,
  'trk.events': `Événements reçus`,
  'trk.eyebrow': `Suivi côté serveur`,
  'trk.title': `Vos conversions, enfin visibles par vos outils publicitaires`,
  'trk.body': `Les bloqueurs de publicités et les navigateurs filtrent une partie de vos événements avant qu'ils n'atteignent Meta ou Google Ads. Le suivi côté serveur les envoie depuis un sous-domaine qui vous appartient, dédupliqués, et uniquement avec le consentement de vos visiteurs.`,
  'trk.cta': `Fiabiliser mon suivi`,
  'trk.f1.t': `GTM côté serveur`,
  'trk.f1': `Un conteneur serveur sur un sous-domaine first-party : moins de conversions perdues à cause des bloqueurs et des restrictions des navigateurs.`,
  'trk.f2.t': `API Conversions Meta`,
  'trk.f2': `Événements navigateur et serveur dédupliqués, avec un plan de tests qui montre ce qui est reçu et la qualité de la correspondance.`,
  'trk.f3.t': `Consentement respecté`,
  'trk.f3': `Branché sur votre plateforme de consentement : seules les données autorisées par vos visiteurs sont transmises.`,
  'lead.eyebrow': `Alerte prospects`,
  'lead.title': `Chaque demande traitée en quelques secondes`,
  'lead.body': `Un prospect qui attend va voir ailleurs. Dès qu'un formulaire est envoyé ou qu'une annonce génère un contact, il est créé dans votre CRM et votre équipe est alertée sur WhatsApp, par e-mail ou sur Slack.`,
  'lead.cta': `Répondre plus vite`,
  'lead.form': `Demande de devis`,
  'lead.send': `Envoyer`,
  'lead.now': `à l'instant`,
  'lead.n1': `Nouveau prospect : Acme · demande de devis`,
  'lead.n2': `Nouveau prospect depuis le site`,
  'lead.n3': `Contact créé · Acme`,
  'lead.f1.t': `Directement dans votre CRM`,
  'lead.f1': `Chaque nouveau prospect est créé ou mis à jour automatiquement dans votre CRM, sans copier-coller.`,
  'lead.f2.t': `Alerte instantanée`,
  'lead.f2': `WhatsApp, e-mail ou Slack : la bonne personne est prévenue en quelques secondes et peut rappeler pendant que le prospect est encore chaud.`,
  'lead.f3.t': `Testé de bout en bout`,
  'lead.f3': `Un scénario Make ou Zapier testé du formulaire jusqu'à l'alerte, avec une mini-documentation pour que votre équipe puisse le maintenir.`,
  'acc.eyebrow': `Loi européenne sur l'accessibilité`,
  'acc.title': `Votre site est-il conforme, oui ou&nbsp;non&nbsp;?`,
  'acc.body': `Depuis juin 2025, la loi européenne sur l'accessibilité (European Accessibility Act, EAA) s'applique à de nombreux sites marchands. Un site non conforme risque des sanctions, dont des amendes financières : leur montant et leurs modalités dépendent de chaque État membre de l'Union européenne, et la France en prévoit. Notre rapport vous répond clairement : votre site est-il conforme ou non, quels points posent problème, et dans quel ordre les corriger.`,
  'acc.fine.t': `En France, mieux vaut vérifier avant un contrôle`,
  'acc.fine.1': `7 500 €`,
  'acc.fine.1s': `d'amende, à partir de`,
  'acc.fine.2': `3 000&nbsp;€/jour`,
  'acc.fine.2s': `d'astreinte si l'injonction est ignorée`,
  'acc.fine.3': `300 000 €`,
  'acc.fine.3s': `de plafond de l'astreinte`,
  'acc.fine.src': `Source :`,
  'acc.cta': `Vérifier mon site`,
  'acc.rep': `Rapport d'accessibilité`,
  'acc.elig': `Site concerné par la loi`,
  'acc.yes': `Oui`,
  'acc.list': `<li class="is-ok">Textes alternatifs</li><li class="is-ko">Contrastes des couleurs</li><li class="is-ok">Navigation au clavier</li><li class="is-ko">Libellés des formulaires</li><li class="is-ok">Parcours de paiement</li>`,
  'acc.score': `Points conformes<b>3 sur 5 contrôlés</b>`,
  'acc.fix': `Liste de correctifs<b>2 points à corriger</b>`,
  'acc.f1.t': `Éligibilité`,
  'acc.f1': `Votre site est-il concerné ? Nous vérifions votre situation au regard de la loi, exemption des micro-entreprises comprise.`,
  'acc.f2.t': `Point par point`,
  'acc.f2': `Pour chaque point contrôlé (contrastes, textes alternatifs, formulaires, navigation au clavier, parcours d'achat) : conforme ou non conforme, avec la page concernée.`,
  'acc.f3.t': `Un plan de correction clair`,
  'acc.f3': `Une liste de correctifs priorisée, prête à transmettre à votre développeur : vous savez exactement ce qu'il reste à faire.`,

  // ---------- Revenue & Data ----------
  'tag.new': `Nouveau`,

  // ---------- Verification ----------
  'ver.gate': `Validation`,
  'ver.list': `<li>Requêtes DNS</li><li>Test de réception</li><li>Consentement avant balises</li><li>Accord du client</li>`,
  'ver.escrow': `Paiement<b>Débité après votre accord</b>`,
  'ver.match': `Avancement<b>72 % · tests en cours</b>`,
  'ver.eyebrow': `Livraison suivie et vérifiée`,
  'ver.title': `Suivez chaque étape. Payez à 100 %.`,
  'ver.body': `Votre commande avance de 0 à 100 % sous vos yeux, dans votre espace client. Avant la livraison, une étape de validation lance requêtes DNS, e-mails tests et contrôle du chargement des scripts. Votre carte est autorisée à la commande et débitée seulement après votre accord.`,
  'ver.cta': `Voir comment ça marche`,
  'ver.f1.t': `Délais garantis`,
  'ver.f1': `Standard en 5 jours ouvrés, Express en 48 h, Flash en 24 h. En retard ? Vous êtes remboursé de 50 % du prix HT en Standard, de 100 % en Express ou en Flash.`,
  'ver.f2.t': `Suivi en temps réel`,
  'ver.f2': `Chaque étape de votre commande est visible dans votre espace client, des accès reçus jusqu'au rapport de tests final.`,
  'ver.f3.t': `Paiement à la livraison vérifiée`,
  'ver.f3': `Paiement sécurisé par Stripe : votre carte est autorisée à la commande et débitée seulement une fois le travail vérifié et validé par vous.`,

  // ---------- Why it matters / audiences ----------
  'aud.eyebrow': `Pourquoi c'est important`,
  'aud.title': `Grande ou petite structure, les règles et les enjeux sont les mêmes`,
  'aud.lead': `Les messageries, les régulateurs et vos clients ne font pas de différence selon votre taille. Ce qui change, c'est ce qu'une erreur vous coûte.`,
  'aud.s1.l': `Messageries`,
  'aud.s1': `Depuis février 2024, Gmail et Yahoo exigent SPF, DKIM et DMARC des expéditeurs en volume, et Outlook a suivi en 2025. Les e-mails non authentifiés sont filtrés ou rejetés.`,
  'aud.s2.l': `Accessibilité`,
  'aud.s2': `Depuis le 28 juin 2025, l'European Accessibility Act s'applique à de nombreux sites de vente en ligne de l'Union européenne, hors micro-entreprises. Chaque client bloqué est une vente perdue.`,
  'aud.s3.l': `Cookies`,
  'aud.s3': `La CNIL et ses homologues européens contrôlent les sites qui déposent des traceurs sans consentement, et sanctionnent des organisations de toutes tailles, du grand groupe à la petite entreprise.`,
  'aud.for': `Recommandé`,
  'aud.c1.t': `Grandes entreprises`,
  'aud.c1': `Des dizaines d'outils envoient des e-mails et déposent des traceurs en votre nom. Un seul service mal configuré suffit à envoyer tout un domaine en spam, ou à exposer votre marque au régulateur.`,
  'aud.c2.t': `PME et ETI`,
  'aud.c2': `Pas d'expert en interne, mais les mêmes obligations que les grands groupes. Un devis qui part en spam ou une bannière qui trace avant le consentement vous coûte des ventes et vous expose.`,
  'aud.c3.t': `E-commerçants`,
  'aud.c3': `L'accessibilité est désormais attendue jusqu'au paiement, chaque conversion manquée par vos outils affaiblit vos campagnes, et chaque demande sans réponse est un panier qui part ailleurs.`,
  'aud.c4.t': `Indépendants et particuliers`,
  'aud.c4': `Un site vitrine, un portfolio, votre propre nom de domaine pour vos e-mails : vos devis et vos réponses doivent arriver, et dès que votre site utilise de la mesure d'audience ou de la publicité, le consentement des visiteurs s'applique à vous aussi.`,
  'aud.c5.t': `Agences`,
  'aud.c5': `La conformité et la délivrabilité de vos clients rejaillissent sur vous. Confiez la partie technique à un spécialiste et livrez un rapport de tests partageable à chaque client.`,
  'aud.c6.t': `Associations et startups`,
  'aud.c6': `Appels aux dons, newsletters, formulaires d'inscription : vos messages doivent arriver, et les personnes qui vous font confiance méritent un consentement propre dès le premier jour, sans recruter une équipe pour ça.`,
  'aud.cta.text': `Vous ne savez pas par où commencer ? Parlez-nous de votre site, nous vous orientons vers le bon service.`,
  'aud.cta1': `Demander un diagnostic gratuit`,
  'aud.cta2': `Voir les offres et tarifs`,

  // ---------- Standards / why / integrations ----------
  'std.title': `Conçu selon les règles des messageries et des régulateurs`,
  'std.gdpr': `<span class="is-on">RGPD</span><span>ePrivacy</span>`,
  'why.label': `Pourquoi Stanza`,
  'why.bullets': `Choisir une diapositive`,
  'why.1.l': `Qualité premium`,
  'why.1': `Des experts vérifiés, un travail soigné, un rapport que vous serez fier de partager.`,
  'why.2.l': `Rapport qualité/prix`,
  'why.2': `Un travail d'expert à prix fixe. Pas de devis, pas d'abonnement, pas de surprise.`,
  'why.3.l': `Suivi de 0 à 100 %`,
  'why.3': `Suivez votre commande étape par étape depuis votre espace client.`,
  'why.4.l': `Paiement sécurisé par Stripe`,
  'why.4': `Votre carte n'est débitée qu'à 100 %, une fois la livraison vérifiée.`,
  'why.5.l': `Réseau de spécialistes`,
  'why.5': `Des spécialistes vérifiés, choisis pour votre tâche.`,
  'why.6.l': `La vitesse quand il le faut`,
  'why.6': `Standard en 5 jours, Express en 48 h, Flash en 24 h. Garanti, ou remboursé.`,
  'why.cta': `Voir les offres et tarifs`,
  'int.title': `Compatible avec vos outils`,
  'int.cta': `Une question sur vos outils ?`,

  // ---------- FAQ (home) ----------
  'faq.title': `Vos questions, nos réponses`,
  'faq.1.q': `De quoi avez-vous besoin pour commencer ?`,
  'faq.1.a': `Après le paiement, un court formulaire vous demande votre domaine, votre messagerie, la plateforme de votre site et un moyen de nous donner un accès temporaire à votre hébergeur DNS, à votre CMS ou à vos outils. Votre spécialiste commence dès que l'accès est confirmé.`,
  'faq.2.q': `Quand ma carte est-elle débitée ?`,
  'faq.2.a': `À la commande, Stripe autorise votre carte. Le montant n'est prélevé qu'une fois la validation réussie et le rapport de livraison approuvé par vous, sous 7 jours. Si le travail ne passe pas la validation, l'autorisation est levée et vous ne payez rien.`,
  'faq.7.q': `Comment suivre ma commande ?`,
  'faq.7.a': `Depuis votre espace client, vous voyez votre commande avancer de 0 à 100 % : accès reçus, configuration, tests, rapport final. C'est aussi là que vous validez la livraison avant que votre carte soit débitée.`,
  'faq.3.q': `En combien de temps livrez-vous ?`,
  'faq.3.a': `La livraison standard prend 5 jours ouvrés. Si vous êtes pressé, choisissez Express (48 h maximum) ou Flash (24 h maximum) sur la page des tarifs. Chaque délai est garanti : en cas de retard, vous êtes remboursé de 50 % du prix HT en Standard et de 100 % du prix HT en Express ou en Flash.`,
  'faq.4.q': `Mes e-mails ne partiront-ils plus en spam ?`,
  'faq.4.a': `L'authentification est la base que Google, Yahoo et Microsoft exigent désormais pour arriver en boîte de réception. Nous la configurons et la vérifions de bout en bout. Le contenu et la réputation d'envoi comptent aussi : votre rapport contient des recommandations sur ces deux points.`,
  'faq.5.q': `Quels outils et plateformes prenez-vous en charge ?`,
  'faq.5.a': `Axeptio, Cookiebot et Didomi sur Shopify, Webflow et WordPress ; Google Workspace et Microsoft 365 pour les e-mails ; Google Tag Manager et Meta pour le suivi ; Make ou Zapier pour les automatisations. Si vos outils sont différents, contactez-nous : nous vous disons sous 24 h si cela rentre dans nos services.`,
  'faq.6.q': `Faites-vous du conseil juridique ?`,
  'faq.6.a': `Non. Stanza réalise la mise en œuvre technique. Votre politique de confidentialité et vos bases légales doivent être validées par votre DPO ou votre conseil, et le diagnostic d'accessibilité n'est ni un audit RGAA complet ni une attestation de conformité.`,
  'cta.title': `Un travail de qualité et durable,<br>avec un suivi intégral.`,
  'cta.btn': `Voir les offres et tarifs`,

  // ---------- Footer ----------
  'ft.product': `Produit`,
  'ft.who': `Pour qui ?`,
  'ft.agencies': `Agences`,
  'ft.services': `Services`,
  'ft.a11y': `Diagnostic d'accessibilité`,
  'ft.tracking': `Suivi côté serveur`,
  'ft.leads': `Alerte prospects`,
  'ft.verification': `Vérification`,
  'ft.pay': `Paiement à la livraison`,
  'ft.platforms': `Plateformes`,
  'ft.websites': `Sites web`,
  'ft.email': `Messageries`,
  'ft.tracktools': `Suivi et automatisation`,
  'ft.cmp': `Plateformes de consentement`,
  'ft.faq': `FAQ tarifs`,
  'ft.about': `Qui sommes-nous`,
  'ft.aboutus': `À propos`,
  'ft.legal': `Mentions légales`,
  'ft.privacy': `Politique de confidentialité`,
  'ft.terms': `Conditions générales de vente`,
  'ft.cookies': `Gérer les cookies`,
  'ft.abuse': `Signaler un abus`,

  // ---------- Pricing page ----------
  'pr.title': `Tarifs — Stanza`,
  'pr.desc': `Services premium à prix fixes : consentement cookies, accessibilité, délivrabilité e-mail, suivi côté serveur et alerte prospects. Suivis de 0 à 100 %, débités seulement après vérification.`,
  'pr.ogtitle': `Tarifs Stanza — une tâche, un prix fixe`,
  'pr.eyebrow': `Tarifs`,
  'pr.h1': `Choisissez votre service.<br>Nous nous occupons du reste.`,
  'pr.lead': `Une échéance demain ou la semaine prochaine ? On vous offre le bon expert, au bon moment. Chaque offre est détaillée ici, ligne par ligne, avant de commander.`,
  'pr.pt1': `Paiement sécurisé, débité après validation`,
  'pr.pt2': `Prix fixe, sans abonnement`,
  'pr.pt3': `Délai garanti, ou remboursé`,
  'pr.pt4': `Suivi total du produit`,
  'pr.speed': `Délai de livraison`,
  'pr.speed.std': `5 jours ouvrés`,
  'pr.speed.exp': `48 h maximum`,
  'pr.speed.fla': `24 h maximum`,
  'pr.speed.note': `Délai garanti : en cas de retard, <b>50 % du prix HT est remboursé en Standard</b> et <b>100 % en Express ou en Flash</b>. Le délai court dès que nous avons tous les accès nécessaires, et uniquement en jours ouvrés. Non applicable aux packs, dont le délai de livraison est établi après commande.`,
  'pr.error': `Le paiement n'a pas pu démarrer. Réessayez ou contactez-nous.`,
  'pr.packs.t': `Plusieurs services, un seul passage, un meilleur prix`,
  'pr.packs.l': `Notre meilleur rapport qualité/prix : un seul expert s'occupe de tout dans le bon ordre, avec un rapport regroupé, pour moins cher que les mêmes services pris séparément.`,
  'pr.p1.e': `Pilier 1`,
  'pr.p1.t': `Conformité`,
  'pr.p1.l': `Ce que la loi attend de votre site : un consentement qui tient vraiment, et un premier regard sur l'accessibilité.`,
  'pr.p2.e': `Pilier 2`,
  'pr.p2.l': `Ce qui transforme vos e-mails, vos publicités et vos formulaires en ventes : des messages qui arrivent, des conversions comptées, des prospects rappelés vite.`,
  'pr.m.e': `Volume`,
  'pr.m.t': `Plusieurs domaines à authentifier ?`,
  'pr.m.l': `Pour les agences et les groupes multi-marques. Indiquez le nombre de domaines à traiter : un expert vous répond avec un devis et une estimation du temps nécessaire, dans votre espace client.`,
  'pr.how.t': `Comment se passe une commande`,
  'pr.how.1.t': `Vous choisissez et commandez`,
  'pr.how.1': `Paiement sécurisé par Stripe. Votre carte est autorisée, pas débitée.`,
  'pr.how.2.t': `Vous partagez vos accès`,
  'pr.how.2': `Un formulaire de 2 minutes : votre domaine, votre site, vos outils et comment nous donner un accès temporaire.`,
  'pr.how.3.t': `Vous suivez de 0 à 100 %`,
  'pr.how.3': `Un expert vérifié réalise le travail dans le délai choisi ; vous suivez chaque étape dans votre espace client.`,
  'pr.how.4.t': `Vous validez, puis vous payez`,
  'pr.how.4': `Contrôles automatisés et rapport de tests. Votre carte n'est débitée qu'après votre accord.`,
  'pr.faq.t': `Questions sur les tarifs`,
  'pr.faq.1.q': `Les prix sont-ils hors taxes ?`,
  'pr.faq.1.a': `Oui. Tous les prix de cette page sont affichés hors taxes (HT) et sont des paiements uniques, sans abonnement.`,
  'pr.faq.2.q': `Quelle différence entre Standard, Express et Flash ?`,
  'pr.faq.2.a': `Le travail et le rapport sont exactement les mêmes ; seul le délai change. Standard : 5 jours ouvrés. Express : 48 h maximum. Flash : 24 h maximum. Le délai démarre dès que nous avons les accès nécessaires, et il est garanti : en cas de retard, vous êtes remboursé de 50 % du prix HT en Standard, de 100 % du prix HT en Express ou en Flash. Les packs ont un prix unique et leur délai de livraison est établi après la commande. Les demandes multi-domaines n'ont pas d'option fixe : l'expert estime le délai dans votre devis.`,
  'pr.faq.8.q': `Que se passe-t-il si le délai n'est pas tenu ?`,
  'pr.faq.8.a': `Vous êtes remboursé. En Standard, nous remboursons la moitié du prix HT ; en Express ou en Flash, la totalité du prix HT. Le travail est tout de même terminé et livré. Le délai court à partir du moment où nous avons tous les accès nécessaires, et uniquement en jours ouvrés. Les packs ne sont pas concernés : leur délai de livraison est établi après commande. Les demandes multi-domaines sur devis non plus : leur délai est fixé dans le devis.`,
  'pr.faq.3.q': `Quand ma carte est-elle débitée ?`,
  'pr.faq.3.a': `À la commande, Stripe autorise seulement votre carte. Le montant est prélevé une fois la validation réussie et le rapport de livraison approuvé par vous, sous 7 jours. Si le travail ne passe pas la validation, l'autorisation est levée et vous ne payez rien.`,
  'pr.faq.4.q': `Les licences des logiciels sont-elles incluses ?`,
  'pr.faq.4.a': `Non. Les abonnements aux outils tiers (plateforme de consentement, hébergement du serveur de suivi, Make, Zapier, CRM, WhatsApp) sont facturés par leurs éditeurs. Chaque fiche indique précisément ce qui est inclus et ce qui ne l'est pas.`,
  'pr.faq.5.q': `Pourquoi le suivi côté serveur demande-t-il un consentement en place ?`,
  'pr.faq.5.a': `Le suivi côté serveur ne remplace pas le consentement : il n'envoie que les données que vos visiteurs ont autorisées. Si vous n'avez pas encore de plateforme de consentement conforme, le Pack Complet l'installe d'abord, puis branche le suivi.`,
  'pr.faq.6.q': `J'ai plusieurs sites ou domaines, ou un besoin particulier.`,
  'pr.faq.6.a': `Pour plusieurs domaines e-mail, utilisez la demande de devis multi-domaines : indiquez le nombre de domaines et un expert vous envoie un devis avec une estimation du délai. Pour tout le reste, <a href="#" data-tally="contact">contactez-nous</a> : nous répondons sous 24 h.`,
  'pr.cta.t': `Premium, sécurisé, suivi à 100 %.<br>Lequel vous faut-il ?`,

  // ---------- Success page ----------
  'ok.title': `Commande confirmée — Stanza`,
  'ok.h1': `Commande confirmée.<br>Passons à la mise en route.`,
  'ok.lead': `Votre carte a été autorisée. Elle ne sera débitée qu'une fois votre livraison validée par tous les contrôles.`,
  'ok.s1': `Parlez-nous de votre domaine, de votre site et de vos outils (2 minutes).`,
  'ok.s2': `Un spécialiste vérifié est attribué et commence le travail.`,
  'ok.s3': `Suivez votre commande de 0 à 100 % dans votre espace client, puis validez le rapport de tests dans le délai choisi.`,
  'ok.cta': `Compléter la mise en route`,
  'ok.back': `Retour à Stanza`,
};
