// French version of every text marked data-i18n / data-i18n-attr in public/*.html.
// The English text lives in the HTML itself. Values may contain HTML
// (except the ones used in attributes: titles, descriptions, aria-labels).
// `npm run check:i18n` lists missing or unused keys.
export const FR = {
  // ---------- Head / accessibility ----------
  'home.title': `Stanza — Conformité, délivrabilité et suivi, réglés pour vous`,
  'home.desc': `Stanza règle la technique de votre site et de vos e-mails : consentement cookies, accessibilité, SPF/DKIM/DMARC, suivi côté serveur et alerte prospects. Périmètre fixe, réalisé par un spécialiste, vérifié avant paiement.`,
  'home.ogtitle': `Stanza — Restez conforme. Vendez en confiance.`,
  'home.ogdesc': `Consentement cookies, accessibilité, délivrabilité e-mail, suivi côté serveur et alerte prospects, réalisés par des spécialistes vérifiés et contrôlés avant paiement.`,
  'a11y.skip': `Aller au contenu principal`,
  'a11y.home': `Accueil Stanza`,
  'a11y.nav': `Navigation principale`,
  'a11y.lang': `Langue`,

  // ---------- Header ----------
  'nav.solutions': `Solutions`,
  'nav.compliance': `Conformité`,
  'nav.consent': `Consentement cookies`,
  'nav.consent.s': `Une bannière qui bloque vraiment les traceurs`,
  'nav.a11y': `Diagnostic d'accessibilité <i class="tag">Nouveau</i>`,
  'nav.a11y.s': `Repérez ce qui bloque vos clients`,
  'nav.verified': `Livraison vérifiée`,
  'nav.verified.s': `Contrôlée avant paiement`,
  'nav.inbox': `Délivrabilité e-mail`,
  'nav.tracking': `Suivi côté serveur <i class="tag">Nouveau</i>`,
  'nav.leads': `Alerte prospects <i class="tag">Nouveau</i>`,
  'nav.leads.s': `CRM + WhatsApp, e-mail ou Slack`,
  'nav.pack1.s': `Cookies + accessibilité`,
  'nav.pack2.s': `E-mails, conversions, prospects`,
  'nav.pack3': `Pack Complet <i class="tag">Les 5</i>`,
  'nav.pack3.s': `Tout en un seul passage`,
  'nav.pack4.s': `Pour les agences et groupes multi-marques`,
  'nav.resources': `Ressources`,
  'nav.support': `Assistance`,
  'nav.help': `Centre d'aide`,
  'nav.help.s': `Des réponses rapides`,
  'nav.check': `Diagnostic gratuit`,
  'nav.check.s': `Nous regardons votre domaine et votre site`,
  'nav.contactus': `Nous contacter`,
  'nav.contactus.s': `Parlez à notre équipe`,
  'nav.company': `Entreprise`,
  'nav.become': `Devenir spécialiste`,
  'nav.become.s': `Rejoindre le réseau`,
  'nav.who': `Pour qui ?`,
  'nav.who.s': `Entreprises, indépendants, agences…`,
  'nav.news': `Newsletter`,
  'nav.news.s': `Actualité conformité et délivrabilité`,
  'nav.blog': `Blog`,
  'nav.blog.text': `Nos guides sur SPF, DKIM, DMARC, le consentement et l'accessibilité.`,
  'nav.blog.cta': `Lire le blog`,
  'nav.pricing': `Tarifs`,
  'nav.start': `Commencer`,
  'nav.contact': `Contacter l'équipe`,
  'nav.login': `Connexion`,

  // ---------- Hero ----------
  'hero.eyebrow': `Conformité · Revenue &amp; Data`,
  'hero.title': `Restez conforme.<br>Vendez en confiance.`,
  'hero.lead': `Une bannière cookies qui bloque vraiment les traceurs, des e-mails qui arrivent en boîte de réception, des conversions qui remontent à vos outils publicitaires et des prospects rappelés en quelques secondes. Cinq chantiers techniques, réalisés par un spécialiste et vérifiés avant d'être payés.`,
  'hero.cta': `Découvrir nos services`,
  'hero.cta2': `Pourquoi c'est important`,
  'hero.tablist': `Services Stanza`,
  'tab1.label': `Délivrer`,
  'tab1.text': `SPF, DKIM et DMARC sur chaque service qui envoie en votre nom, pour que vos e-mails arrivent en boîte de réception et pas en spam.`,
  'tab2.label': `Se conformer`,
  'tab2.text': `Votre plateforme de consentement installée, et chaque script non essentiel bloqué tant que le visiteur n'a pas dit&nbsp;oui.`,
  'tab3.label': `Vérifier`,
  'tab3.title': `Validation avant paiement`,
  'tab3.text': `Chaque livraison passe des contrôles automatisés avant que votre carte soit&nbsp;débitée.`,
  'stage.pill': `<i>En attente</i><i>Valide</i>`,
  'stage.state': `<i>Bloqué</i><i>Chargé</i>`,
  'stage.stay': `<i>Bloqué</i><i>Bloqué</i>`,
  'stage1.steps': `<li>Audit de la zone DNS…</li><li>Publication du SPF…</li><li>Signature DKIM…</li><li>Application de DMARC…</li><li>Vérification du logo BIMI…</li>`,
  'stage1.kicker': `Authentification DNS`,
  'stage1.right': `Authentification`,
  'stage2.steps': `<li>Analyse de 42 balises…</li><li>Installation de la CMP…</li><li>Catégories de consentement…</li><li>Blocage des scripts…</li><li>Test du Consent Mode v2…</li>`,
  'stage2.banner': `<p class="consent__title">Votre vie privée compte</p><p class="consent__text">Nous utilisons des cookies de mesure et de publicité uniquement avec votre accord.</p><div class="consent__btns"><span>Tout refuser</span><span class="consent__accept">Accepter</span></div><span class="cursor" aria-hidden="true"></span>`,
  'stage2.right': `Scripts tiers`,
  'stage2.mode': `Consent Mode v2 · <b>accordé</b>`,
  'stage3.steps': `<li>Requêtes DNS…</li><li>Envoi d'e-mails tests…</li><li>Analyse des pages clés…</li><li>Collecte des preuves…</li><li>En attente de votre accord…</li>`,
  'stage3.brand': `Validation`,
  'stage3.kicker': `Commande n° ST-2048 · acme.co`,
  'stage3.checks': `<li>SPF résolu en 10 requêtes DNS max.</li><li>Signature DKIM valide</li><li>Rapports DMARC reçus</li><li>Bannière affichée avant toute balise</li><li>Aucune balise avant consentement</li><li>Validé par vous</li>`,
  'stage3.right': `Contrôles réussis`,
  'stage3.escrow': `<i>Autorisé</i><i>Débité</i>`,
  'stage3.small': `Votre carte n'est débitée qu'une fois tous les contrôles réussis.`,

  // ---------- Services overview ----------
  'svc.eyebrow': `Ce que nous réglons`,
  'svc.title': `Deux piliers, cinq services`,
  'svc.lead': `Chaque service a un périmètre fixe : fait une fois, fait bien, par un spécialiste, avec un rapport de tests comme preuve. Prenez-les un par un ou en pack.`,
  'svc.p1': `Conformité`,
  'svc.p1.text': `Ce que la loi attend de votre site, et qui fonctionne vraiment.`,
  'svc.p2.text': `Ce qui transforme vos e-mails, vos publicités et vos formulaires en ventes.`,
  'svc.packs': `Besoin de plusieurs services ? Les packs <a href="/pricing#pack-compliance">Conformité</a>, <a href="/pricing#pack-revenue">Revenue</a> et <a href="/pricing#pack-complete">Complet</a> les regroupent en un seul passage, avec un seul spécialiste.`,

  // ---------- Deliverability ----------
  'deliv.eyebrow': `Délivrabilité e-mail`,
  'deliv.title': `En boîte de réception, pas dans les spams`,
  'deliv.body': `Google, Yahoo et Microsoft rejettent désormais les e-mails non authentifiés. Un devis qui part en spam est un devis que personne ne lit. Stanza configure SPF, DKIM, DMARC, BIMI et MX sur votre domaine, pour que chaque facture, relance et newsletter arrive chez la bonne personne.`,
  'deliv.cta': `Sécuriser mes e-mails`,
  'deliv.typing': `Régler la délivrabilité de acme.co`,
  'deliv.to': `à moi · Principale`,
  'deliv.inbox': `Réception`,
  'deliv.subject': `Votre facture de mars est disponible`,
  'deliv.report': `Rapport DMARC`,
  'deliv.aligned': `alignés`,
  'deliv.f1': `Authentification DNS complète pour chaque service qui envoie en votre nom : Google Workspace, Microsoft 365, votre CRM et votre outil de newsletter.`,
  'deliv.f2.t': `BIMI et enregistrements MX`,
  'deliv.f2': `Votre logo à côté de vos e-mails dans les messageries compatibles, un routage MX propre et aucun enregistrement contradictoire.`,
  'deliv.f3.t': `Vérification Postmaster`,
  'deliv.f3': `Google Postmaster Tools et rapports DMARC en place : vous voyez la réputation de votre domaine au lieu de la deviner.`,

  // ---------- Compliance ----------
  'head.title': `Là où l'audit s'arrête,<br>le correctif commence...`,
  'comp.banner': `<b>Cookies ?</b><small>Mesure et publicité uniquement avec votre accord.</small><span class="browser__btns"><i>Refuser</i><i>Accepter</i></span>`,
  'comp.cats': `Catégories de consentement`,
  'comp.toggles': `<li>Nécessaires<span class="toggle is-on is-locked"></span></li><li>Mesure d'audience<span class="toggle" data-toggle></span></li><li>Marketing<span class="toggle"></span></li>`,
  'comp.blocked': `<b>12</b> scripts bloqués avant consentement`,
  'comp.eyebrow': `Cookies et accessibilité`,
  'comp.title': `Le consentement d'abord, sur chaque page`,
  'comp.body': `Une bannière seule ne prouve rien si vos balises se déclenchent quand même. Nous déployons Axeptio, Cookiebot ou Didomi sur Shopify, Webflow ou WordPress et bloquons chaque script non essentiel jusqu'à l'accord du visiteur. Puis nous repérons ce qui empêche vos clients en situation de handicap d'acheter.`,
  'comp.cta': `Mettre mon site en conformité`,
  'comp.f1.t': `Un consentement qui tient`,
  'comp.f1': `Axeptio, Cookiebot ou Didomi, configurés avec vos catégories et votre charte, testés avant et après consentement, avec un rapport pour votre DPO.`,
  'comp.f2.t': `Blocage des scripts et Consent Mode v2`,
  'comp.f2': `Mesure d'audience, pixels et widgets attendent le consentement. Google Consent Mode v2 est branché pour que vos mesures restent exploitables.`,
  'comp.f3.t': `Diagnostic d'accessibilité`,
  'comp.f3': `Vos pages clés analysées, de l'accueil au paiement, et une liste de correctifs priorisée pour votre développeur. Une première étape avant un audit complet.`,

  // ---------- Revenue & Data ----------
  'tag.new': `Nouveau`,
  'rev.title': `Chaque conversion comptée, chaque prospect rappelé`,
  'rev.body': `Les bloqueurs de publicités et les restrictions des navigateurs cachent une partie de vos ventes à vos outils publicitaires, et un prospect qui attend va voir ailleurs. Nous envoyons vos conversions côté serveur, dans le respect du consentement, et alertons votre équipe dès qu'une demande arrive.`,
  'rev.cta': `Fiabiliser mon suivi`,
  'rev.events': `Événements serveur`,
  'rev.list': `<li><b>Purchase</b><span>navigateur + serveur</span><i>dédupliqué</i></li><li><b>Lead</b><span>navigateur + serveur</span><i>dédupliqué</i></li><li><b>AddToCart</b><span>serveur</span><i>reçu</i></li>`,
  'rev.lead': `Nouveau prospect · formulaire du site<b>Ajouté au CRM, équipe alertée</b>`,
  'rev.consent': `Consentement respecté<b>Seules les données autorisées partent</b>`,
  'rev.f1.t': `GTM côté serveur`,
  'rev.f1': `Vos événements envoyés depuis un sous-domaine qui vous appartient : moins de conversions perdues à cause des bloqueurs et des restrictions des navigateurs.`,
  'rev.f2.t': `API Conversions Meta`,
  'rev.f2': `Événements navigateur et serveur dédupliqués, avec un plan de tests qui montre ce qui est reçu et la qualité de la correspondance.`,
  'rev.f3.t': `Alerte prospect instantanée`,
  'rev.f3': `Un scénario Make ou Zapier ajoute chaque prospect à votre CRM et prévient votre équipe sur WhatsApp, par e-mail ou sur Slack en quelques secondes.`,

  // ---------- Verification ----------
  'ver.gate': `Validation`,
  'ver.list': `<li>Requêtes DNS</li><li>Test de réception</li><li>Consentement avant balises</li><li>Accord du client</li>`,
  'ver.escrow': `Paiement<b>Débité après votre accord</b>`,
  'ver.match': `Spécialiste attribué<b>selon votre besoin</b>`,
  'ver.eyebrow': `Livraison vérifiée`,
  'ver.title': `Payez un résultat, vérifié par des contrôles`,
  'ver.body': `Chaque tâche est réalisée par un spécialiste vérifié et passe une étape de validation : requêtes DNS, e-mails tests et contrôle du chargement des scripts. Votre carte est autorisée à la commande et débitée seulement une fois la validation réussie.`,
  'ver.cta': `Voir comment ça marche`,
  'ver.f1.t': `Rapide quand il le faut`,
  'ver.f1': `Des périmètres fixes : pas d'audit à planifier, pas de devis à relancer. Livraison standard en 5 jours ouvrés, ou Express en 48 h et Flash en 24 h.`,
  'ver.f2.t': `Contrôles automatisés`,
  'ver.f2': `Tests DNS et vérification du chargement des scripts à chaque livraison, avec un rapport à partager avec votre équipe.`,
  'ver.f3.t': `Paiement à la livraison vérifiée`,
  'ver.f3': `Votre carte est autorisée via Stripe et débitée seulement une fois le travail vérifié et validé par vous.`,

  // ---------- Why it matters / audiences ----------
  'aud.eyebrow': `Pourquoi c'est important`,
  'aud.title': `Grande ou petite structure, les règles et les enjeux sont les mêmes`,
  'aud.lead': `Les messageries, les régulateurs et vos clients ne font pas de différence selon votre taille. Ce qui change, c'est ce qu'une erreur vous coûte.`,
  'aud.s1.l': `Messageries`,
  'aud.s1': `Depuis février 2024, Gmail et Yahoo exigent SPF, DKIM et DMARC des expéditeurs en volume, et Outlook a suivi en 2025. Les e-mails non authentifiés sont filtrés ou rejetés.`,
  'aud.s2.l': `Accessibilité`,
  'aud.s2': `Depuis le 28 juin 2025, l'European Accessibility Act s'applique à de nombreux sites de vente en ligne de l'Union européenne, hors micro-entreprises. Chaque client bloqué est une vente perdue.`,
  'aud.s3.l': `Cookies`,
  'aud.s3': `La CNIL et ses homologues européens contrôlent les sites qui déposent des traceurs sans consentement, et sanctionnent des organisations de toutes tailles, du grand groupe à la petite entreprise.`,
  'aud.for': `Recommandé`,
  'aud.c1.t': `Grandes entreprises`,
  'aud.c1': `Des dizaines d'outils envoient des e-mails et déposent des traceurs en votre nom. Un seul service mal configuré suffit à envoyer tout un domaine en spam, ou à exposer votre marque au régulateur.`,
  'aud.c2.t': `PME et ETI`,
  'aud.c2': `Pas d'expert en interne, mais les mêmes obligations que les grands groupes. Un devis qui part en spam ou une bannière qui trace avant le consentement vous coûte des ventes et vous expose.`,
  'aud.c3.t': `E-commerçants`,
  'aud.c3': `L'accessibilité est désormais attendue jusqu'au paiement, chaque conversion manquée par vos outils affaiblit vos campagnes, et chaque demande sans réponse est un panier qui part ailleurs.`,
  'aud.c4.t': `Indépendants et particuliers`,
  'aud.c4': `Un site vitrine, un portfolio, votre propre nom de domaine pour vos e-mails : vos devis et vos réponses doivent arriver, et dès que votre site utilise de la mesure d'audience ou de la publicité, le consentement des visiteurs s'applique à vous aussi.`,
  'aud.c5.t': `Agences`,
  'aud.c5': `La conformité et la délivrabilité de vos clients rejaillissent sur vous. Confiez la partie technique à un spécialiste et livrez un rapport de tests partageable à chaque client.`,
  'aud.c6.t': `Associations et startups`,
  'aud.c6': `Appels aux dons, newsletters, formulaires d'inscription : vos messages doivent arriver, et les personnes qui vous font confiance méritent un consentement propre dès le premier jour, sans recruter une équipe pour ça.`,
  'aud.cta.text': `Vous ne savez pas par où commencer ? Parlez-nous de votre site, nous vous orientons vers le bon service.`,
  'aud.cta1': `Demander un diagnostic gratuit`,
  'aud.cta2': `Voir les offres et tarifs`,

  // ---------- Standards / why / integrations ----------
  'std.title': `Conçu selon les règles des messageries et des régulateurs`,
  'std.gdpr': `<span class="is-on">RGPD</span><span>ePrivacy</span>`,
  'why.label': `Pourquoi Stanza`,
  'why.bullets': `Choisir une diapositive`,
  'why.1.l': `Services standardisés`,
  'why.1': `Périmètre fixe. Pas de devis, pas d'audit, pas de dérive.`,
  'why.2.l': `Délivrabilité e-mail`,
  'why.2': `Du dossier spam à la boîte de réception, preuves à l'appui.`,
  'why.3.l': `RGPD et CMP`,
  'why.3': `Votre bannière est en ligne et chaque traceur non essentiel attend le consentement.`,
  'why.4.l': `Paiement sécurisé par Stripe`,
  'why.4': `Votre carte n'est débitée qu'une fois la livraison vérifiée.`,
  'why.5.l': `Réseau de spécialistes`,
  'why.5': `Des spécialistes vérifiés, choisis pour votre tâche.`,
  'why.6.l': `La vitesse quand il le faut`,
  'why.6': `Standard en 5 jours, Express en 48 h, Flash en 24 h.`,
  'why.cta': `Voir les offres et tarifs`,
  'int.title': `Compatible avec vos outils`,
  'int.cta': `Une question sur vos outils ?`,

  // ---------- FAQ (home) ----------
  'faq.title': `Vos questions, nos réponses`,
  'faq.1.q': `De quoi avez-vous besoin pour commencer ?`,
  'faq.1.a': `Après le paiement, un court formulaire vous demande votre domaine, votre messagerie, la plateforme de votre site et un moyen de nous donner un accès temporaire à votre hébergeur DNS, à votre CMS ou à vos outils. Votre spécialiste commence dès que l'accès est confirmé.`,
  'faq.2.q': `Quand ma carte est-elle débitée ?`,
  'faq.2.a': `À la commande, Stripe autorise votre carte. Le montant n'est prélevé qu'une fois la validation réussie et le rapport de livraison approuvé par vous, sous 7 jours. Si le travail ne passe pas la validation, l'autorisation est levée et vous ne payez rien.`,
  'faq.3.q': `En combien de temps livrez-vous ?`,
  'faq.3.a': `La livraison standard prend 5 jours ouvrés. Si vous êtes pressé, choisissez Express (48 h maximum) ou Flash (24 h maximum) sur la page des tarifs avant de commander.`,
  'faq.4.q': `Mes e-mails ne partiront-ils plus en spam ?`,
  'faq.4.a': `L'authentification est la base que Google, Yahoo et Microsoft exigent désormais pour arriver en boîte de réception. Nous la configurons et la vérifions de bout en bout. Le contenu et la réputation d'envoi comptent aussi : votre rapport contient des recommandations sur ces deux points.`,
  'faq.5.q': `Quels outils et plateformes prenez-vous en charge ?`,
  'faq.5.a': `Axeptio, Cookiebot et Didomi sur Shopify, Webflow et WordPress ; Google Workspace et Microsoft 365 pour les e-mails ; Google Tag Manager et Meta pour le suivi ; Make ou Zapier pour les automatisations. Si vos outils sont différents, contactez-nous : nous vous disons sous 24 h si cela rentre dans nos services.`,
  'faq.6.q': `Faites-vous du conseil juridique ?`,
  'faq.6.a': `Non. Stanza réalise la mise en œuvre technique. Votre politique de confidentialité et vos bases légales doivent être validées par votre DPO ou votre conseil, et le diagnostic d'accessibilité n'est ni un audit RGAA complet ni une attestation de conformité.`,
  'cta.title': `Conformité et revenus.<br>Tout dans Stanza.`,
  'cta.btn': `Voir les offres et tarifs`,

  // ---------- Footer ----------
  'ft.product': `Produit`,
  'ft.who': `Pour qui ?`,
  'ft.agencies': `Agences`,
  'ft.services': `Services`,
  'ft.a11y': `Diagnostic d'accessibilité`,
  'ft.tracking': `Suivi côté serveur`,
  'ft.leads': `Alerte prospects`,
  'ft.verification': `Vérification`,
  'ft.pay': `Paiement à la livraison`,
  'ft.platforms': `Plateformes`,
  'ft.websites': `Sites web`,
  'ft.email': `Messageries`,
  'ft.tracktools': `Suivi et automatisation`,
  'ft.cmp': `Plateformes de consentement`,
  'ft.faq': `FAQ tarifs`,
  'ft.about': `Qui sommes-nous`,
  'ft.aboutus': `À propos`,
  'ft.legal': `Mentions légales`,
  'ft.privacy': `Politique de confidentialité`,
  'ft.terms': `Conditions générales de vente`,
  'ft.cookies': `Gérer les cookies`,
  'ft.abuse': `Signaler un abus`,

  // ---------- Pricing page ----------
  'pr.title': `Tarifs — Stanza`,
  'pr.desc': `Prix fixes pour le consentement cookies, le diagnostic d'accessibilité, la délivrabilité e-mail, le suivi côté serveur et l'alerte prospects. Livraison Standard, Express ou Flash, débitée seulement après vérification.`,
  'pr.ogtitle': `Tarifs Stanza — une tâche, un prix fixe`,
  'pr.eyebrow': `Tarifs`,
  'pr.h1': `Une tâche. Un prix fixe.<br>Vérifié avant paiement.`,
  'pr.lead': `Pas de devis, pas d'audit à planifier : chaque service a un périmètre et un prix fixes, hors taxes. Votre carte est autorisée à la commande et débitée seulement une fois la livraison validée.`,
  'pr.pt1': `Périmètre et prix fixes`,
  'pr.pt2': `Débité après validation`,
  'pr.pt3': `Rapport de tests à chaque livraison`,
  'pr.speed': `Délai de livraison`,
  'pr.speed.std': `5 jours ouvrés`,
  'pr.speed.exp': `48 h maximum`,
  'pr.speed.fla': `24 h maximum`,
  'pr.error': `Le paiement n'a pas pu démarrer. Réessayez ou contactez-nous.`,
  'pr.packs.t': `Plusieurs services, un seul passage, un meilleur prix`,
  'pr.packs.l': `Un seul spécialiste s'occupe de tout dans le bon ordre, avec un rapport regroupé. Vous payez moins cher que les mêmes services pris séparément.`,
  'pr.p1.e': `Pilier 1`,
  'pr.p1.t': `Conformité`,
  'pr.p1.l': `Ce que la loi attend de votre site : un consentement qui tient vraiment, et un premier regard sur l'accessibilité.`,
  'pr.p2.e': `Pilier 2`,
  'pr.p2.l': `Ce qui transforme vos e-mails, vos publicités et vos formulaires en ventes : des messages qui arrivent, des conversions comptées, des prospects rappelés vite.`,
  'pr.m.e': `Volume`,
  'pr.m.t': `Plusieurs domaines à authentifier ?`,
  'pr.m.l': `Pour les agences et les groupes multi-marques. Les délais Express et Flash sont sur devis pour ce pack.`,
  'pr.how.t': `Comment se passe une commande`,
  'pr.how.1.t': `Vous choisissez et commandez`,
  'pr.how.1': `Paiement sécurisé par Stripe. Votre carte est autorisée, pas débitée.`,
  'pr.how.2.t': `Vous partagez vos accès`,
  'pr.how.2': `Un formulaire de 2 minutes : votre domaine, votre site, vos outils et comment nous donner un accès temporaire.`,
  'pr.how.3.t': `Un spécialiste réalise`,
  'pr.how.3': `Dans le délai choisi : 5 jours ouvrés, 48 h ou 24 h.`,
  'pr.how.4.t': `Vous validez, puis vous payez`,
  'pr.how.4': `Contrôles automatisés et rapport de tests. Votre carte n'est débitée qu'après votre accord.`,
  'pr.faq.t': `Questions sur les tarifs`,
  'pr.faq.1.q': `Les prix sont-ils hors taxes ?`,
  'pr.faq.1.a': `Oui. Tous les prix de cette page sont affichés hors taxes (HT) et sont des paiements uniques, sans abonnement.`,
  'pr.faq.2.q': `Quelle différence entre Standard, Express et Flash ?`,
  'pr.faq.2.a': `Le travail et le rapport sont exactement les mêmes ; seul le délai change. Standard : 5 jours ouvrés (7 pour le pack 6 domaines). Express : 48 h maximum. Flash : 24 h maximum. Le délai démarre dès que nous avons les accès nécessaires.`,
  'pr.faq.3.q': `Quand ma carte est-elle débitée ?`,
  'pr.faq.3.a': `À la commande, Stripe autorise seulement votre carte. Le montant est prélevé une fois la validation réussie et le rapport de livraison approuvé par vous, sous 7 jours. Si le travail ne passe pas la validation, l'autorisation est levée et vous ne payez rien.`,
  'pr.faq.4.q': `Les licences des logiciels sont-elles incluses ?`,
  'pr.faq.4.a': `Non. Les abonnements aux outils tiers (plateforme de consentement, hébergement du serveur de suivi, Make, Zapier, CRM, WhatsApp) sont facturés par leurs éditeurs. Chaque fiche indique précisément ce qui est inclus et ce qui ne l'est pas.`,
  'pr.faq.5.q': `Pourquoi le suivi côté serveur demande-t-il un consentement en place ?`,
  'pr.faq.5.a': `Le suivi côté serveur ne remplace pas le consentement : il n'envoie que les données que vos visiteurs ont autorisées. Si vous n'avez pas encore de plateforme de consentement conforme, le Pack Complet l'installe d'abord, puis branche le suivi.`,
  'pr.faq.6.q': `J'ai plusieurs sites ou domaines, ou un besoin particulier.`,
  'pr.faq.6.a': `Le pack 6 domaines couvre la plupart des agences et des groupes multi-marques. Pour tout le reste, <a href="#" data-tally="contact">contactez-nous</a> : nous répondons sous 24 h avec un devis ferme.`,
  'pr.cta.t': `Vous hésitez<br>entre plusieurs offres ?`,

  // ---------- Success page ----------
  'ok.title': `Commande confirmée — Stanza`,
  'ok.h1': `Commande confirmée.<br>Passons à la mise en route.`,
  'ok.lead': `Votre carte a été autorisée. Elle ne sera débitée qu'une fois votre livraison validée par tous les contrôles.`,
  'ok.s1': `Parlez-nous de votre domaine, de votre site et de vos outils (2 minutes).`,
  'ok.s2': `Un spécialiste vérifié est attribué et commence le travail.`,
  'ok.s3': `Vous recevez votre rapport de tests dans le délai choisi.`,
  'ok.cta': `Compléter la mise en route`,
  'ok.back': `Retour à Stanza`,
};
